version: '3.8'

services:
  db:
      image: postgres:13
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1234
        POSTGRES_DB: postgres
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
    
  backend:
    depends_on:
      - db
    image: backend
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: postgres

  frontend:
    depends_on:
      - backend
    image: frontend
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "4200:4200"

volumes:
  pgdata: